import "./globals.css";

import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";

import { cn } from "@/lib/utils";

import { Header } from "@/components/custom/header";
import { Footer } from "@/components/custom/footer";
import { getGlobalPageData } from "@/data/loaders";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Nunito({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getGlobalPageData();
  const { topNav, footer } = data?.data;

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <Header data={topNav}/>
        {children}
        <Footer data={footer}/>
      </body>
    </html>
  );
}
